pipelines:
  bufallo-visualizer:
    group: markwaveai
    materials:
      git:
        url: https://github.com/eswar689143-dot/markwaveai-demo.git
        branch: main

    environment_variables:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/bufallo_visualizer
      CONTAINER_NAME: bufallo_visualizer
      PORT: "8081"

    stages:
      - build:
          jobs:
            build-image:
              tasks:
                - type: exec
                  command: bash
                  arguments:
                    - -c
                    - |
                      cd bufallo_visualizer
                      docker build -t $IMAGE_NAME:latest .

    

      - push:
          jobs:
            push-image:
              tasks:
                - type: exec
                  command: bash
                  arguments:
                    - -c
                    - |
                      echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                      docker push $IMAGE_NAME:latest

      - deploy:
          jobs:
            deploy-container:
              tasks:
                - type: exec
                  command: bash
                  arguments:
                    - -c
                    - |
                      docker rm -f $CONTAINER_NAME || true
                      docker compose pull
                      docker compose up -d
