pipelines:
  emi-calculator:
    group: markwaveai
    materials:
      git:
        url: https://github.com/eswar689143-dot/markwaveai-demo.git
        branch: main

    environment_variables:
      IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/emi_calculator
      CONTAINER_NAME: emi_calculator
      PORT: "8082"

    stages:
      - build:
          jobs:
            build-image:
              tasks:
                - task:
                    type: exec
                    attributes:
                      command: bash
                      arguments:
                        - -c
                        - |
                          cd emi_calculator
                          docker build -t $IMAGE_NAME:latest .

      - push:
          jobs:
            push-image:
              tasks:
                - task:
                    type: exec
                    attributes:
                      command: bash
                      arguments:
                        - -c
                        - |
                          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                          docker push $IMAGE_NAME:latest

      - deploy:
          jobs:
            deploy-container:
              tasks:
                - task:
                    type: exec
                    attributes:
                      command: bash
                      arguments:
                        - -c
                        - |
                          docker rm -f $CONTAINER_NAME || true
                          docker compose pull
                          docker compose up -d
