pipelines:
  otp-app:
    group: apps
    materials:
      git:
        type: git
        url: https://github.com/eswar689143-dot/gocd-config-repo.git
        branch: main

    stages:
      - deploy:
        jobs:
          deploy-job:
            tasks:
              - exec:
                command: bash
                arguments:
                  - -c
                  - |
                    docker compose up -d otp_app